apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  group: argoproj.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: workflows
    kind: Workflow
    shortNames:
    - wf