apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kubebuild.fullname" . }}
  labels:
    chart: {{ template "kubebuild.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kubebuild.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubebuild.fullname" . }}
  namespace: {{ .Release.Namespace }} 