apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubebuild.fullname" . }}
  labels:
    chart: {{ template "kubebuild.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config: |
    {{- if .Values.useReleaseAsInstanceID }}
    instanceID: {{ .Release.Name }}
    {{- else }}
    instanceID: {{ .Values.instanceID }}
    {{- end }}
    artifactRepository:
      {{- if .Values.useDefaultArtifactRepo }}
      s3:
        {{- if .Values.useStaticCredentials }}
        accessKeySecret:
          key: {{ .Values.artifactRepository.s3.accessKeySecret.key }}
          name: {{ .Values.artifactRepository.s3.accessKeySecret.name | default (printf "%s-%s" .Release.Name "s3-user") }}
        secretKeySecret:
          key: {{ .Values.artifactRepository.s3.secretKeySecret.key }}
          name: {{ .Values.artifactRepository.s3.secretKeySecret.name | default (printf "%s-%s" .Release.Name "s3-user") }}
        {{- end }}
        bucket: {{ .Values.artifactRepository.s3.bucket }}
        endpoint: {{ .Values.artifactRepository.s3.endpoint }}
        insecure: {{ .Values.artifactRepository.s3.insecure }}
      {{- end}}
    executorImage: "{{ .Values.executorImage.repository }}:{{ .Values.executorImage.tag }}"
