apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kubebuild.fullname" . }}-launcher
  labels:
    chart: {{ template "kubebuild.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs: ["*"]
- apiGroups: ["", "extensions"]
  resources:
  - deployments
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch