{{- if semverCompare ">=2.10-0" .Capabilities.TillerVersion.SemVer }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    chart: {{ template "kubebuild.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: argoproj.io
  version: v1alpha1
  names:
    kind: Workflow
    plural: workflows
    shortNames: ["wf"]
  scope: Namespaced
{{- end -}}