{{- if .Values.useStaticCredentials }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "kubebuild.fullname" . }}
  labels:
    chart: {{ template "kubebuild.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  accesskey: {{ .Values.s3Secrets.accessKey}}
  secretkey: {{ .Values.s3Secrets.secretKey}}
{{- end }}