apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kube-launcher.fullname" . }}
  labels:
    app: {{ template "kube-launcher.name" . }}
    chart: {{ template "kube-launcher.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kube-launcher.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kube-launcher.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: {{ .Values.app.args }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: K8S_TOKEN
            value: {{ .Values.app.k8sToken }}
          - name: CLUSTER_TOKEN
            value: {{ .Values.app.clusterToken }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
