apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    chart: {{ template "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get